#macro FORCE_SPAWN_ON      -1
#macro FORCE_SURFACE_BIOME -1
#macro FORCE_CAVE_BIOME    -1

enum WORLDGEN_SALT {
    CAVE           =  0x81CFA386D,
    
    WALL           =  0xFF0BD9144,
    BASE           = -0x17E8FD1A9,
    FOLIAGE        = -0x02D81BAC5,
    
    BIOME_HEAT     =  0x7F33A10A2,
    BIOME_HUMIDITY = -0xA441027BD
}

#macro TILE_SIZE_BIT 4
#macro TILE_SIZE (1 << TILE_SIZE_BIT)
#macro TILE_SIZE_H (TILE_SIZE / 2)

#macro CHUNK_SIZE_X_BIT 4
#macro CHUNK_SIZE_Y_BIT 4
#macro CHUNK_SIZE_X (1 << CHUNK_SIZE_X_BIT)
#macro CHUNK_SIZE_Y (1 << CHUNK_SIZE_Y_BIT)
#macro CHUNK_SIZE_Z 8
#macro CHUNK_SIZE_Z_BIT ((1 << CHUNK_SIZE_Z) - 1)

#macro CHUNK_SIZE_WIDTH  (CHUNK_SIZE_X * TILE_SIZE)
#macro CHUNK_SIZE_HEIGHT (CHUNK_SIZE_Y * TILE_SIZE)

#macro CHUNK_SIZE_WIDTH_H  (CHUNK_SIZE_WIDTH  / 2)
#macro CHUNK_SIZE_HEIGHT_H (CHUNK_SIZE_HEIGHT / 2)

#macro CHUNK_DEPTH_DEFAULT     3
#macro CHUNK_DEPTH_WALL        0
#macro CHUNK_DEPTH_TREE_BACK   2
#macro CHUNK_DEPTH_TREE_FRONT  5
#macro CHUNK_DEPTH_TREE        choose(CHUNK_DEPTH_TREE_BACK, CHUNK_DEPTH_TREE_FRONT)
#macro CHUNK_DEPTH_PLANT_BACK  1
#macro CHUNK_DEPTH_PLANT_FRONT 4
#macro CHUNK_DEPTH_PLANT       choose(CHUNK_DEPTH_PLANT_BACK, CHUNK_DEPTH_PLANT_FRONT)
#macro CHUNK_DEPTH_LIQUID      7

#macro CHUNK_SURFACE_PADDING (TILE_SIZE * 3)

#macro CHUNK_SURFACE_WIDTH  (CHUNK_SIZE_WIDTH  + (CHUNK_SURFACE_PADDING * 2))
#macro CHUNK_SURFACE_HEIGHT (CHUNK_SIZE_HEIGHT + (CHUNK_SURFACE_PADDING * 2))